### ISSUE TITLE
Postgres search implementation: need to precompute indices?

### ISSUE THREAD

**Issue by mhuyck** [greenelab/py3-adage-backend#10]
Our initial implementation for searching with PostgreSQL builds the index and queries it on the fly. For example, see the `.get_queryset()` methods in the `ExperimentViewSet` and `GeneViewSet` implementations in `adage/analyze/views.py` and `adage/genes/views.py`.

The TrigramSimilarity performance is of particular concern since it will be called repeatedly from the front end as the user types in order to present a list of matching terms to select.

We need to run some experiments to examine how these search interfaces scale as data are added to the database and also as the number of concurrent requests hits the backend.

I am surprised that the demo site built for #8 performs as well as it does, so my concerns may be unwarranted. At the same time, this architecture does not look like it will scale well and I am guessing that our good performance arises from a beastly AWS database server.

Some reference materials for further research:

- https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/search/#performance
- https://www.postgresql.org/docs/current/textsearch-tables.html#TEXTSEARCH-TABLES-INDEX

**Comment by dongbohu** [comment]
It's possible to add postgres-specific search indexes in `models.py`:
https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/indexes/
Alternatively, these indexes can be added by psql commands, as described in the Postgres doc URL (the second one above).

**Comment by mhuyck** [comment]
I noticed that too. I suspect that's maybe on the path of what I was thinking about. One advantage to generating the index on the fly is that you don't need to think about when to update the index since it's happening right before each query. I suspect that won't be sustainable, though, which is why I filed this issue.

The requirement then becomes (1) precompute the search index, *and* (2) re-compute or update that index as new data are added to the system.

We had scripts to do these things with Elasticsearch. Not sure what the equivalent maintenance steps will be with Postgres. Some examples I see have database triggers, which I typically avoid but maybe those are the right solution here since we're already locked into Postgres for full text search.

**Comment by dongbohu** [comment]
Like other regular indexes, a field's search index will be updated automatically when the field value is updated, so database triggers are not necessary. The reason why I didn't add them is because:
  * the performance w/o them seems acceptable
  * it is a postgres-specific feature, so I am reluctant to add

**Comment by dongbohu** [comment]
Postgres-specific indexes will be added in deployment step.
