### ISSUE TITLE
Split model description into multiple metadata

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/py3-adage-backend#12]
@dongbohu The [model query](https://py3-adage.greenelab.com/api/v1/mlmodels/) returns some useful metadata about the models, but it is all condensed into a single description field, `desc_html`.

I'd prefer to have this split up into separate fields, and not have preformatted HTML. I'd like to have:

`authors`, `publisher`, `year`, `url`, and then finally `description`.

@dhimmel from your work with metatags in Manubot, is there typically a field for funding sources, like grants? 

@dhimmel and @cgreene Is there any other useful model metadata you can think of?

**Comment by cgreene** [comment]
I don't think you could assume that every model will have all of these fields. Some will be published. Others will not yet be published. Others will never be published. Probably some but not all will have funding sources. It would be interesting to see this type of information included, but a full text description should be allowed and may, in some cases, be the only thing available.

**Comment by vincerubinetti** [comment]
Yes they might not always be available. But if they are available, they should be split up into separate fields so I can properly display them and don't have to parse a string. I will make sure that the frontend can always handle any field being blank.

**Comment by vincerubinetti** [comment]
Maybe `affiliation` as well, for university?

**Comment by cgreene** [comment]
It would be helpful to consider if what you're asking is for a set of keys and values to be stored associated with the model or if you're asking for _specific_ keys and potentially associated values. The database design would be different. Since many will be blank and not applicable for many models, it's possible you want the former instead of the latter, but I'm not sure.

**Comment by vincerubinetti** [comment]
I'm not familiar enough with backend design to know the difference between those two.

These would be fields that the "user" (whoever is loading the model into the database) could specify, and that the `mlmodels` end point would return as separate fields/keys if they were specified by the "user". Then I will handle looking for them in the query results, and displaying a placeholder if they are blank/undefined/null/etc.

I'm pretty sure @dongbohu will know what I'm after here though. We can discuss it in person as well.

**Comment by dhimmel** [comment]
> @dhimmel from your work with metatags in Manubot, is there typically a field for funding sources, like grants?

I am missing context here. We can chat more about what an "mlmodel" is to see whether funding information is relevant and what standards may exist here.

**Comment by vincerubinetti** [comment]
Okay I think this is the complete list.

- `title` - `string` - title/name of the model
- `authors` - `[string]` - authors of the model ("et al" can be added programmatically)
- `publisher` - `string` - most notable journal where model was published, if any
- `year` - `string | number` - year when model was published in the journal above, if any
- `affiliations` - `[string]` - university/company affiliations, if any
- `funders` - `[string]` - funders, if any
- `description` - `string` - text (not html) description of the model
- `url` - `string` - primary url associated with the model, if any. this could be the online place where the model was published, it could be the author's website or blog post about the model, it could be the university's website.
- `references` - `[string]` - any references or urls that might be helpful in understanding or using the model. perhaps links to other related papers
- `license` - `string` - license of the model data

**Comment by dongbohu** [comment]
It's probably better to set all fields to `string` type, because the `array` type is not supported by all databases. For the one that includes multiple values, we can use comma as a delimiter.

**Comment by vincerubinetti** [comment]
Are we not choosing a particular database that will be enforced? If not, it's your call. It may get a little muddy if the values can have commas in them, like if a university or a funding source has a comma as part of their name (not sure how common that is).

**Comment by dongbohu** [comment]
The database model should support at least two database types: `Postgres` and `SQLite`, so any db-specific feature could be an issue.

**Comment by dongbohu** [comment]
The fields that you like them to be arrays can be set to multiple lines, and each line is a separate entry. It will be better than using comma as a delimiter.

**Comment by dongbohu** [comment]
Fixed by PR #16.
