### ISSUE TITLE
rename model endpoint

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/py3-adage-backend#13]
I'd like to rename `mlmodels` to just `models` in the endpoint url. I don't think `ml` adds anything, and is kinda arbitrary and hard to remember. None of the other queries have qualifiers before their nouns (eg, it's not `humangenes`).

Ps I'm aware it stands for "machine learning". It's just that all the other queries are single nouns. And anyone using the software already knows that "models" in this context means "machine learning models".

**Comment by dongbohu** [comment]
I will change it.

**Comment by dongbohu** [comment]
FIxed in PR #14
