### ISSUE TITLE
Improve gene search results

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/py3-adage-backend#19]
@dongbohu I forgot how you told me the search works currently. I'm not sure what fields it searches by, but it should probably search all fields, at least by default. And perhaps we could even add filters down the road (eg. only search entrez id's and descriptions).

Right now it's hard for me to tell what it searches by. For example, here's a results list with no search term:
![image](https://user-images.githubusercontent.com/8326331/69739800-5282c800-1106-11ea-920a-dc87f80e055f.png)

But when I type "pyo", nothing shows up:
![image](https://user-images.githubusercontent.com/8326331/69739823-5f9fb700-1106-11ea-80d5-5669c2531be7.png)

So maybe description isn't being searched. On the other hand, typing in "PA" yields some results with "PA" in their description, but only yields two results, so it seems like it's not searching the `systematic_name` field:
![image](https://user-images.githubusercontent.com/8326331/69740007-a7bed980-1106-11ea-8237-c1b416a865bc.png)

**Comment by dongbohu** [comment]
Are you using “search” or “autocomplete” parameter? The former does full text search, and the latter does trigram search.

**Comment by vincerubinetti** [comment]
I'm using `search`, but shouldn't it still return something for `pyo` since there's an exact match? I'm assuming `search` does simple substring matching?

**Comment by dongbohu** [comment]
No, full text search is very different from substring match. It does word search with stemming considered. For a search like “pyo”, trigram search will be better.

**Comment by vincerubinetti** [comment]
I think this might be closeable?
