### ISSUE TITLE
rename entrezid to entrez_id

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/py3-adage-backend#36]
All fields in and returned from the database seem to be `underscore_case`, except for `entrezid`.

Entrez ID is a common term, and it seems like people take "entrez" and "id" as separate words, as they should:

https://www.biostars.org/p/394654/

![image](https://user-images.githubusercontent.com/8326331/73882654-72361b00-4830-11ea-907b-98edce4a188d.png)
![image](https://user-images.githubusercontent.com/8326331/73882664-76facf00-4830-11ea-833f-05fdfd34e728.png)
![image](https://user-images.githubusercontent.com/8326331/73882680-7cf0b000-4830-11ea-9da5-6082c8133e0e.png)

**Comment by dongbohu** [comment]
Fixed in PR #55.
