### ISSUE TITLE
Rename (and divide) "analyze" django app

### ISSUE THREAD

**Issue by dongbohu** [greenelab/py3-adage-backend#6]
When reviewing #1, we had a discussion on whether the Django app `analyze` should be renamed from the verb to a noun (such as `analysis`). 

@mhuyck also suggests that this app can be divided into two, one takes care of data sources (experiments and samples), the other takes care of all the other models currently in `analyze`. This probably makes sense, but it needs some code refactoring since the models will be in different modules.

**Comment by mhuyck** [comment]
After reviewing the way Django projects are usually laid out, I think I'm backing off the idea of splitting this into two new apps in favor of migrating the code from this `analyze` "app" into the `adage` project. Inside that project it may still make sense to separate the "annotated source data" from the "ADAGE model data," but all of these models seem to be central to the `adage-backend` project and cannot be separated out easily as reusable app modules (as we have done with `django-genes` and `django-organisms`) in the way Django defines them.

**Comment by dongbohu** [comment]
I forgot to mention: No matter how `analyze` app will be modified, the management commands and tests in original app (see `adage` repo) should be migrated to Python 3 too.

**Comment by dongbohu** [comment]
Since the app names are usually plural, `analyses` seems  to be a better name.

**Comment by dongbohu** [comment]
Fixed in PR #55.
