### ISSUE TITLE
"wall_of_name" in "Gene" model 

### ISSUE THREAD

**Issue by dongbohu** [greenelab/py3-adage-backend#7]
`Gene` model (defined in `genes/models.py`), was copied from `django-genes` package:
https://github.com/dongbohu/django-genes/blob/master/genes/models.py

In its method `wall_of_name`, I wonder why `self.standard_name` was added to the `names_string` twice. One was on line 60:
https://github.com/greenelab/py3-adage-backend/blob/177bb3826758d76e45ffd19b51d99e908c0b7754/adage/genes/models.py#L60
the other was on lines 69-70:
https://github.com/greenelab/py3-adage-backend/blob/master/adage/genes/models.py#L69-L70

@cgreene and @mhuyck: Is this a bug, or added on purpose so that `standard_name` will have a higher weight during text search? 

Another question that is related: when Elasticsearch builds indexes based on
https://github.com/dongbohu/django-genes/blob/master/genes/templates/search/indexes/genes/gene_text.txt
since `standard_name` and `systematic_name` are already included in `wall_of_names`, why are they still included in this file?

**Comment by cgreene** [comment]
I think it was a hack to create a higher weight during text search. I imagine it was also to give them an even higher weight.

**Comment by dongbohu** [comment]
It might be better to use "weighting queries" in Django/Postgres:
https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/search/#weighting-queries
For example, we can give `standard_name` a weight of `A`, all the other fields weight of `B`, `C` or `D`, or we can use our own weighting system.

**Comment by mhuyck** [comment]
Take another look at lines 61 and 70. I agree this is confusing, but notice that the two versions of the `standard_name` being added to `wall_of_name` are different. In line 61, `standard_name` is included as-is. At line 70, a regular expression is used to remove anything matching the `num` pattern (digits `[0-9]`, defined at line 9) before appending that to the `wall_of_name` as well.

This strikes me as a sort of "manual" re-tokenization. It may not be necessary with Postgres full text search, but I suspect it was done that way initially for a reason and we should be sure we don't introduce any regressions by removing it.

I would recommend importing all of the tests from `django-genes` before making too many changes.

**Comment by dongbohu** [comment]
@mhuyck: Yes, I knew that the function `wall_of_name` did some conversion when adding the gene's standard and systematic names at the end. I tried to simulate it with `annotate` method but eventually gave up, because Django doesn't offer that much flexibility when adding extra annotation field.

The original `django-genes` repo has a few test cases written with Tastypie. We should port them to django-rest-framework.

**Comment by dongbohu** [comment]
Implemented in PR #8.
