### ISSUE TITLE
New "Experiment" Search API

### ISSUE THREAD

**Issue by dongbohu** [greenelab/py3-adage-backend#9]
Here is a summary of my discussion with @cgreene on the search API of `Experiment` model:

Fields used for full text search should include:
(1) experiment `accession`
(2) experiment `name`
(3) experiment `description`
(4) Information of samples related to current experiment

(1)-(3) are located in current `Experiment` model, (4) can be collected from associated models `Sample`, `SampleAnnotation` and `AnnotationType`. It should be a plain text field that combines the following information of all samples that are associated with the current experiment:
(4a) sample `name`
(4b) sample `ml_data_source`
(4c) annotation values of current sample

(4a) and (4b) are located in `Sample` model, (4c) can be collected from `SampleAnnotation` model. 
@cgreene, in (4c), should we include both annotation type names and annotation values, or only annotation values? In other words, do you prefer (4c) in the format of:
```
description: Pseudomonas aeruginosa 9.5 hour static coculture with human CFBEs, replicate 1
nucleic_acid: RNA
medium: MEM, 0.4% arginine
genotype: WT
od: 9.5 hours
growth_setting_1: Biofilm
growth_setting_2: Static
strain: PA14
temperature: 37
additional_notes: 9.5 h biofilms
biotic_int_lv_1: Human
biotic_int_lv_2: Lung epithelial cells (CFBE41o- cells)
```
(the string before `:` on each line is annotation type name, the one after `:` is the corresponding annotation value.)
or in the format of:
```
Pseudomonas aeruginosa 9.5 hour static coculture with human CFBEs, replicate 1
RNA
MEM, 0.4% arginine
WT
9.5 hours
Biofilm
Static
PA14
37
9.5 h biofilms
Human
Lung epithelial cells (CFBE41o- cells)
```
(in which the strings before `:` are removed)?

**Comment by dongbohu** [comment]
Note that the above new `Experiment` search API is similar to the one used in original adage server's `Sample` search API (implemented by Elasticsearch):
https://github.com/greenelab/adage-server/blob/master/adage/analyze/templates/search/indexes/analyze/sample_text.txt
```
{{ object.name }}
{{ object.ml_data_source }}
Experiments: {% for e in object.experiments.all %}{{ e.accession }}{% endfor %}
Annotations:
{% for k, v in object.get_annotation_items %}<em>{{ k }}:</em> {{ v }}
{% endfor %}
```
but the strings `Experiments:` and `Annotations:` may be unnecessary when used in searching (but they do make the API output more user-friendly). What do you think, @mhuyck?

**Comment by cgreene** [comment]
In terms of formatting the first one looks nicer but in terms of utility for search, i think the second one is nicer. The things that I think are relevant in the example you provided for search are:
MEM arginine
WT
biofilm
static
PA14
human
lung epithelial CFBE41o 

If the others are there it's not the end of the world, but perhaps the fields that have just numbers aren't ideal for search (though, who knows, perhaps 37 is a common enough temperature that folks would search for that).

**Comment by cgreene** [comment]
For example, I'm not sure it's helpful to search over the term "genotype" since all samples probably have that field.

**Comment by dongbohu** [comment]
I was thinking that maybe a user would search by a term like `genetype: WT`, then the results will include experiments whose samples have annotation type `genetype` with value `WT`. 

It's probably possible to search without the annotation type names (the second format) but include annotation type names in API output (the first format). I need to do some tests.

**Comment by cgreene** [comment]
Ahh - if it's apparent to the user that this is possible then perhaps it'd be well-used. How much development time would it add to support that?

**Comment by dongbohu** [comment]
Hard to say exactly how much development time it may take. I have a few idea that I would like to try. If they don't work, I will probably select the most straightforward implementation.
